# AI聊天机器人系统配置
server:
  port: 8080

# 应用统一配置
app:
  # 系统配置
  system:
    max-context-tokens: 8192
    session-timeout: 3600
    websocket:
      ping-interval: 30
      max-reconnect-attempts: 5

  # AI配置
  ai:
    # 系统提示词配置
    system-prompt:
      base: "# 核心指令\n你的首要任务是成为一个乐于助人、知识渊博且安全无害的AI助手。你的核心目标是准确理解用户意图，并提供清晰、结构化且高质量的回答。\n\n# 交互风格\n- **主动澄清:** 当用户问题模糊时，主动提问以澄清意图。\n- **引导对话:** 在回答结束后，自然地提出相关问题或建议，保持对话流畅。\n- **避免循环:** 避免重复性回答，若对话陷入僵局，尝试从新角度解决问题。"
      fallback: "你是一个友善的AI助手，请帮助用户解决问题。"
      enable-persona: true  # 是否启用人设系统提示词
    # 联网搜索判断配置
    web-search-decision:
      timeout-seconds: 5  # AI判断联网搜索需求的超时时间（秒）
      enable-timeout-fallback: true  # 超时时是否采用保守策略（不搜索）
    streaming:
      chunk-size: 16
      delay-ms: 50
    voice:
      asr-model: "whisper-medium"
      tts-voice: "派蒙"  # 使用CosyVoice的默认语音人设

  # Ollama配置
  ollama:
    base-url: "http://localhost:11434"
    model: "yi:6b"
    timeout: 30000
    max-tokens: 4096
    temperature: 0.7
    stream: true

  # Python API配置
  python:
    # 独立服务URL配置 - 每个服务可以有不同的域名和端口
    services:
      # ASR (语音识别) 服务
      asr-url: "ws://localhost:8767/asr"
      
      # TTS (文本转语音) 服务
      tts-url: "http://localhost:50000"
      
      # VAD (语音活动检测) 服务
      vad-url: "http://localhost:5000"
      
      # OCR (图像识别) 服务
      ocr-url: "http://localhost:5000"
    
    # ASR专用配置
    asr:
      health-url: "http://localhost:8768/health"
      enabled: true
    
    # 超时配置（单位：秒）
    timeout:
      # HTTP连接超时
      connect-timeout-seconds: 60
      
      # HTTP读取超时
      read-timeout-seconds: 60
      
      # HTTP写入超时
      write-timeout-seconds: 60
      
      # TTS任务等待超时
      tts-task-timeout-seconds: 60
      
      # Live2D TTS任务等待超时
      live2d-tts-task-timeout-seconds: 60

  # 资源路径配置
  resources:
    base-path: "src/main/resources"
    log-path: "logs"
    data-paths:
      memories: "data/memories"
      personas: "data/personas"
      sessions: "data/sessions"
      worldbook-manual: "src/main/resources/data/worldbook/manual_worldbook.json"
      worldbook-extracted: "src/main/resources/data/worldbook/extracted_worldbook.json"

  # 联网搜索配置
  web-search:
    enabled: false  # 默认禁用联网搜索
    max-results: 5
    timeout-seconds: 10
    default-engine: "duckduckgo"
    enable-fallback: true
    serp-api-key: ""
    bing-api-key: ""

# 记忆系统配置（预留）
# memory:
#   max_short_term: 50
#   max_long_term: 1000
#   summary_trigger_threshold: 20

# 日志配置（主要配置在logback.xml中）
logging:
  config: classpath:logback.xml
